services:
  mongo-ecommerce-nest:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-network
    command: ["mongod", "--noauth"]

volumes:
  mongo-data:

networks:
  mongo-network:
    driver: bridge
